modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="lightingwand"
version="${file.jarVersion}"
displayName="Lighting Wand"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/lighting-wand"
description="Lighting up!"

[[dependencies.lightingwand]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lightingwand]]
    modId="kiwi"
    mandatory=true
    versionRange="[6,7)"
    ordering="NONE"
    side="BOTH"

[modproperties.lightingwand]
    catalogueItemIcon="lightingwand:wand" #Support for Catalogue mod
